name: action learning

on:
  schedule:
    - cron: '40 17 * * *'
  workflow_dispatch:
jobs:
  push-msg:
    name: test push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
      env:
          REFRESH_TOKENS: ${{ secrets.REFRESH_TOKENS }}
          GP_TOKEN: ${{ secrets.GP_TOKEN}}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          PUSHPLUS_TOPIC: ${{ secrets.PUSHPLUS_TOPIC }}
    - name: Run
      shell: bash
      run: |
        pip install -r requirements.txt 
        python main.py
