name: YoudaoNote-checkin

on:
  release:
    types: [published]
#   push:
#   pull_request:
#   watch:
#     types: [ started ]
#   schedule:
#     - cron: '0 18 * * *'

jobs:
  YoudaoNote-checkin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@master
        with:
          python-version: '3.10'

      - name: install-requirement
        run: |
          pip install -r requirements.txt

      - name: checkin
        env:
          USERNAME: ${{ secrets.YDUSERNAME }}
          PASSWORD: ${{ secrets.YDPASSWORD }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: |
          python3 youdaoCheckin.py
